name: Build Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build rz compiler on ${{ matrix.os }} with ${{ matrix.compiler }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
        compiler: [gcc-10, clang]
        include:
          - os: ubuntu-latest
            compiler: gcc-10
          - os: ubuntu-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc-10
          - os: macos-latest
            compiler: clang

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: CC={{ matrix.compiler }} make
